### ISSUE TITLE
MSPC cannot continue error

### ISSUE THREAD

**Issue by LaraBM** [Genometric/MSPC#123] opened 2020-05-13 16:11 UTC
Hello,

Thanks for making a very useful software! 
I am using MSPC to generate consensus peaks for my ATAC-Seq experiments. I want to generate consensus peaks per treatment type which I was successfully able to do for one treatment type; however, it fails for the other treatment types after a certain point. Below is an example of the error message:
```
 .::...Parsing Samples....::. 
    #	            Filename	Read peaks#	Min p-value	Mean p-value	Max p-value	
------	--------------------	-----------	-----------	------------	-----------	`
  1/11	        273E_IC_peak	    116,172	 1.908E-191	  6.663E-004	 9.993E-003	
  2/11	        280D_IC_peak	    137,711	 9.204E-185	  1.290E-003	 9.993E-003	
  3/11	        519C_IC_peak	    139,766	 3.152E-190	  1.465E-003	 9.993E-003	
  4/11	        551A_IC_peak	    151,793	 3.873E-182	  6.876E-004	 9.993E-003	
  5/11	        595D_IC_peak	    131,618	 2.306E-168	  5.484E-004	 9.993E-003	
  6/11	        643C_IC_peak	    148,040	 9.996E-185	  1.167E-003	 9.993E-003	
  7/11	         704_IC_peak	    135,992	 3.030E-191	  6.284E-004	 9.993E-003	
Error: error parsing data: An item with the same key has already been added. Key: -2061531644
You may run mspc with either of [-? | -h | --help] tags for help.
MSPC cannot continue. 
```
I have tried a couple of things but I am getting the same error and I am not really sure how to proceed. This is the basic command (without options) I submit:
`mspc -i *IC_peak.bed -r bio -w 1e-4 -s 1e-8`

Is it possible to get some insight on how I can solve this please? :slightly_smiling_face:

Many thanks,
Lara

**Comment by VJalili** [comment] 2020-05-14 08:05
Thanks for reporting the issue Lara! 

I was not able to reproduce the error, so based on my best guess, I make some changes and released a newer version: 

https://github.com/Genometric/MSPC/releases/tag/v4.0.1

Please replace your mspc version with the above-linked one, then please try again and let me know if it runs successfully.

**Comment by LaraBM** [comment] 2020-05-14 16:39
Hello!

Thank you for looking at it so quickly!

I have run the newer version and it's working perfectly right now, thank you! I have no idea what it was but thank you for fixing it!

Many thanks,
Lara

**Comment by VJalili** [comment] 2020-05-14 17:04
Glad that fixed it! 

For reference, the issue was related to how MSPC handles hash key collisions. Each region (e.g., ChIP-seq peak) mspc reads from an input file receives a hash key. The hash function used to create the hash key has a very low collision probability; we have never faced collision, so we had not implement logic to handle it. My guess is your input `704_IC_peak` somehow managed to cause this collision, and the lack of proper handling cause the error you see. 

Details: https://github.com/Genometric/GeUtilities/pull/93

I am closing this issue, please feel free to reopen it if you encounter a similar issue.

**Closed by VJalili** 2020-05-14 17:04 UTC
Labels: bug

**Comment by VJalili** [comment] 2020-05-19 03:36
@LaraBM I am working on some corner cases that can be related to the issue you reported. However, since I was not able to reproduce that error, I cannot say for certain if the corner cases are resolved for certain. 

Would it be possible for you to share the files `7/11` and `8/11` with me so I can use them to reproduce the error? You can send the files to via a PM to me if you want.
