### ISSUE TITLE
Number of consensus peaks and TruePositives are not changing in different runs

### ISSUE THREAD

**Issue by juylmin** [Genometric/MSPC#164] opened 2022-03-31 23:55 UTC
Hello, 

I have two questions which I think related with each other.

When I run mspc with such various values for -w and -s options like; -w 1e-4 -s 1e-8, -w 1e-4 -s 1e-6, -w 1e-1 -s 1e-3 , I am always getting the same number of consensus peaks.

And also for different runs, the percentage of Background, Weak, Discarded, FalsePositive are always %0,000 while Stringent , Confirmed, TruePositive ones are %100,000. ( Only Read peaks#  changes, expectedly. )

If you could help me to figure out the reasons I will more than appreciate.

**Comment by VJalili** [comment] 2022-04-01 03:08
Hello, 

> And also for different runs, the percentage of Background, Weak, Discarded, FalsePositive are always %0,000 while Stringent , Confirmed, TruePositive ones are %100,000. ( Only Read peaks# changes, expectedly. )

This means the p-value of all the peaks are more stringent than the stringent threshold. Is it possible for you to share a few peaks from your input here? Are p-values on the fifth column? Are they in Phred scale? (i.e., `-log10(p-value)`)

**Comment by juylmin** [comment] 2022-04-01 16:02
Hello, 

Thank you for your answer.

I am trying it with different peaks collected from distinct samples, conditions, cell lines but I am always getting the same result (not the numbers of peaks or consensus peaks but the discarded, weak, etc.). I am using MACS2 as the peakcaller.  

Here is my sample peaks 

This is narrowPeak file

chr1	1009009	1009834	peakcall_er_T47D_peak_1	1536	.	31.45406	158.80745	153.69818	189
chr1	1014811	1015106	peakcall_er_T47D_peak_2	313		.	15.45682	35.60226	31.37941	154
chr1	1015723	1016017	peakcall_er_T47D_peak_3	38		.	3.62388		7.38901		3.83334		65
chr1	1295828	1296201	peakcall_er_T47D_peak_4	42		.	4.86044		7.85993		4.27735		220

Here, when I check the corresponding xls file of this narrowPeak file, I guess the -log10(p-value) is in the seventh column. So I guess I should change that right?

Thank you.

**Comment by VJalili** [comment] 2022-04-01 20:05
That makes sense; MSPC is reading p-value from the fifth column by default, and it seems your file is not in that format. For instance, the third peak in your example has a value `38`, MPSC reads this as p-value in Phred scale, and converts it to `1e-38`, which is much smaller than all the thresholds you provide calling MSPC, hence all the peaks are considered `Stringent`, `Confirmed`, and `True-Positive`, as you experienced. 


>  I guess the -log10(p-value) is in the seventh column.

You should then provide [parser configuration](https://genometric.github.io/MSPC/docs/cli/parser) for MSPC. Simply create a JSON file as the following and [pass it to MSPC](https://genometric.github.io/MSPC/docs/cli/args#input-parser-configuration). 

```shell
$ cat parser_config.json
{
   "Value":8
}

$ .\mspc.exe -i .\rep*.bed -r bio -w 1e-4 -s 1e-8 --parser parser_config.json
```
Note that the columns are zero-based. Please refer to the [parser docs](https://genometric.github.io/MSPC/docs/cli/parser) for details.

**Comment by juylmin** [comment] 2022-04-04 19:58
Hello again. Thank you for your answer. 

`I guess the -log10(p-value) is in the seventh column.`
I checked and according to the regular narrowPeak file format, the pvalue is in the eighth column, which I mentioned wrongly earlier. 

So, pvalue is in the seventh column according to zero-based index. And I made a config file exactly like this:
```
$  head parser_config.json
{
   "Value":7
}
```

and my code is:

` ./mspc -i rep1.narrowPeak rep2.narrowPeak -r bio -w 1e-4 -s 1e-8 --parser parser_config.json
`
However, my results are still coming out like this:

```
.::...Parsing Samples....::.
   #	            Filename	Read peaks#	Min p-value	Mean p-value	Max p-value
----	--------------------	-----------	-----------	------------	-----------
 1/2	...1_peaks	                     6.941	 0,000E+000	  0,000E+000	 0,000E+000
 2/2	...2_peaks	                     6.642	 0,000E+000	  0,000E+000	 0,000E+000

.::..Analyzing Samples...::.
[1/4] Initializing
[2/4] Processing samples
  └── 13.583/13.583,000)(%100,000) peaks processed
[3/4] Performing Multiple testing correction
[4/4] Creating consensus peaks set

.::....Saving Results....::.

.::..Summary Statistics..::.
   #	            Filename	Read peaks#	Background	    Weak	Stringent	Confirmed	Discarded	TruePositive	FalsePositive
----	--------------------	-----------	----------	--------	---------	---------	---------	------------	-------------
 1/2	...1_peaks	                      6.941	    %0,000	  %0,000	 %100,000	 %100,000	   %0,000	    %100,000	       %0,000
 2/2	...2_peaks	                      6.642	    %0,000	  %0,000	 %100,000	 %100,000	   %0,000	    %100,000	       %0,000

.::.Consensus Peaks Count.::.
7.764


```

I am not sure what is wrong. My narrowPeak files (also pvalues) seem normal to me. I tried above with several different datasets, they look like this:

```
==> peakcall_rep1_peaks.narrowPeak <==
chr1	1008890	1009664	peakcall_rep1_peak_2	3177	.	47.90799	324.06671	317.79968	304
chr1	1014838	1015129	peakcall_rep1_peak_3	193	.	6.92270	22.98327	19.36059	138
chr1	1368445	1368725	peakcall_rep1_peak_4	106	.	5.77824	14.07759	10.63954	102
chr1	1690426	1690784	peakcall_rep1_peak_5	148	.	7.26588	18.36732	14.83344	222
chr1	1691149	1691360	peakcall_rep1_peak_6	110	.	6.27890	14.48693	11.03661	133
chr1	1724892	1725221	peakcall_rep1_peak_7	225	.	8.57340	26.25682	22.58289	170
chr1	2142388	2142576	peakcall_rep1_peak_8	91	.	6.10237	12.55328	9.15135	90
chr1	2379425	2379648	peakcall_rep1_peak_9	59	.	4.92725	9.25272	5.95162	88
chr1	3002432	3002666	peakcall_rep1_peak_10	80	.	5.56757	11.41865	8.05182	77

==> peakcall_rep2_peaks.narrowPeak <==
chr1	931192	931490	peakcall_rep2_peak_1	61	.	4.52994	9.46042	6.14773	138
chr1	1008883	1009666	peakcall_rep2_peak_2	3285	.	49.16168	334.76273	328.53088	315
chr1	1368449	1368695	peakcall_rep2_peak_3	75	.	4.99095	10.86717	7.50697	115
chr1	1690412	1690672	peakcall_rep2_peak_4	47	.	4.59400	7.99821	4.73711	77
chr1	2379392	2379623	peakcall_rep2_peak_5	84	.	5.66243	11.79668	8.40873	117
chr1	3002456	3002658	peakcall_rep2_peak_8	28	.	3.67854	5.96639	2.80426	130



```
I also tried to remove unnecessary columns and create a file that only contains 
chr
start
end
name
pval

and tried it without the json file. This time the result is:

```

.::...Parsing Samples....::.
   #	            Filename	Read peaks#	Min p-value	Mean p-value	Max p-value
----	--------------------	-----------	-----------	------------	-----------
 1/2	..._GATA3_rep1_peaks	          0	 1,000E+000	         NaN	 0,000E+000
 2/2	..._GATA3_rep2_peaks	          0	 1,000E+000	         NaN	 0,000E+000

.::..Analyzing Samples...::.
[1/4] Initializing
[2/4] Processing samples
  └── 0/0	(NaN) peaks
[3/4] Performing Multiple testing correction
[4/4] Creating consensus peaks set

.::....Saving Results....::.

.::..Summary Statistics..::.
   #	            Filename	Read peaks#	Background	    Weak	Stringent	Confirmed	Discarded	TruePositive	FalsePositive
----	--------------------	-----------	----------	--------	---------	---------	---------	------------	-------------
 1/2	...1_peaks	                         0	       NaN	     NaN	      NaN	      NaN	      NaN	         NaN	          NaN
 2/2	...2_peaks	                         0	       NaN	     NaN	      NaN	      NaN	      NaN	         NaN	          NaN

.::.Consensus Peaks Count.::.
0


Elapsed time: 00:00:02.5964612
All processes successfully finished.


```

I also wonder why it is not accepting the file containing only the needed columns. This made me think of could the problem be in the first part not giving all of the column indexes in the config.json file? 

Thank you.

**Comment by VJalili** [comment] 2022-04-05 02:59
Thanks for sharing some sample files! 

In your first try MSPC has read peaks from the input but all with `p-value = 0`, and in the second case it did not read any peaks. You configuration seems correct, so I am guessing there should be something wrong with the input you're providing. 

In the MSPC output and the files you shared, I noticed an inconsistency in decimal and thousands separators: 

```
1/2	...1_peaks	                     6.941	 0,000E+000	  0,000E+000	 0,000E+000
```

```
chr1	1008890	1009664	peakcall_rep1_peak_2	3177	.	47.90799	324.06671	317.79968	304
```

`6.941` in the MSPC output is given with `.` as thousands separator, while in the sample `.narrowpeak` file you shared `.` is used as decimal separator, e.g., `47.90799`. MSPC reads your system's culture info and [parses your input accordingly](https://github.com/Genometric/MSPC/blob/4953f6d2bbf4aaca5c17c5dbd010727fd48f78ee/CLI/ParserConfig.cs#L43); however, it seems your system culture setting is inconsistent with the files you provide. I assume changing your system's culture info could be easier than regenerating `.narrowpeak` files, if so, could you please change you system's culture info to the same format as the `.narrowpeak` files and retry calling MSPC?

**Comment by juylmin** [comment] 2022-04-05 18:08
Hello again, thank you for your answer. 
I am working on a supercomputer so when I try to change , display the culture info it is giving me 'permission denied' error. I can ask for help from the manager but it will take time. So, I want to ask if I can adapt the json file according to the .narrowpeak culture ? I read the _culture info_ part of the [https://genometric.github.io/MSPC/docs/cli/parser/](url) but I guess it is not healthy doing that because of this disclaimer:

>The numbers written to the output files generated by MSPC are formatted according to the operating system's settings, independent from the culture setting provided for the input parser.

**Comment by VJalili** [comment] 2022-04-05 19:25
The default culture is set to your system's culture, but you can override it using the parser config: 

```json
{
"Culture":"en-US"
}
```

You can find more information on the [page you also linked](https://genometric.github.io/MSPC/docs/cli/parser/#culture-info). Just make sure you're setting it to the same culture as the one used to generate the `.narrowpeaks`. Maybe `"en-US"` be good enough?!

**Comment by juylmin** [comment] 2022-04-10 13:01
I guess this solved my problem. Thank you so much!I thank for everything though. 

I just want to ask a silly question. My output is looking like this:

Min p-value Mean p-value  Max p-value
----------- ------------  -----------
 0,000E+000   2,104E-006   5,229E-004
 0,000E+000   6,838E-007   2,006E-004
 1,414E-082   1,751E-006   4,032E-004

Are these  0,000E+000 values in Minimum p-val column okay to have?

**Comment by VJalili** [comment] 2022-04-10 22:12
Glad that helped! 

> Are these 0,000E+000 values in Minimum p-val column okay to have?

I assume your p-values are in `-log10(p-value)` scale (please double-check, and if not, [adjust the parser accordingly](https://genometric.github.io/MSPC/docs/cli/parser/#p-value-format)), in this case, peaks with p-values such as `324` will be rounded to `0`. Based on the examples you shared above (specifically, the following peak), it seems you have such peaks in your samples, hence `0.0` in p-value stats is expected. 

```
chr1	1008890	1009664	peakcall_rep1_peak_2	3177	.	47.90799	324.06671	317.79968
```

**Comment by VJalili** [comment] 2022-09-09 23:20
Hello, Anthony! I'm happy to help. Could you please share a few lines of the samples you are using and the arguments you use to call MSPC?

**Comment by AnthonyDohertyTCD** [comment] 2022-09-12 09:35
Hi @VJalili 

I want to obtain the common peaks for 3 biological replicates. My main issue is I am losing the majority of peaks. This happens even when I set very relaxed -w & -s parameters. My -log10(p-value) are in column 8 and hence I set the parser_config.json file accordingly.  


`mspc -i P-BMI-Rep1_peaks.broadPeak P-BMI-Rep2_peaks.broadPeak P-BMI-Rep3_peaks.broadPeak  -r Bio -w 1e-4 -s 1e-8 -c 3 --parser parser_config.json`

![Screenshot 2022-09-12 at 10 31 01](https://user-images.githubusercontent.com/62442736/189620627-96a8cbfd-26c0-474b-8295-df6afa2a9adf.png)

`mspc -i P-BMI-Rep1_peaks.broadPeak P-BMI-Rep2_peaks.broadPeak P-BMI-Rep3_peaks.broadPeak  -r Bio -w 1e-1 -s 1e-2 -c 3 --parser parser_config.json`

![Screenshot 2022-09-12 at 10 31 27](https://user-images.githubusercontent.com/62442736/189620724-e3a5c779-dc76-45b1-88f4-7a917c798119.png)

`cat parser_config.json

{
"Value":7,
"Culture":"en-US"
}
`
`head P-BMI-Rep1_peaks.broadPeak | cut -f 8
4.83396
4.06017
6.79406
5.40592
5.2829
6.75005
6.26792
5.31249
9.62441
7.55559
`

I greatly appreciated your help. 

Kind Regards, 

Anthony

**Comment by VJalili** [comment] 2022-09-12 23:55
Thanks for sharing the screenshots and the arguments you have used. 

For a `Weak` or `Stringent` peak to be `Confirmed` and eventually identified as `TP` or `FP`, it needs to pass two tests: overlapping criteria and combined stringency should satisfy the `-g` threshold (please see [the flowchart on this page](https://genometric.github.io/MSPC/docs/method/about)).

Since you have a decent number of peaks in the `Discarded` set, even when you use very permissive thresholds, I guess your peaks fail the overlapping test. In other words, when you set `-c 3`, a peak will be discarded if it does not overlap with at least one peak from each of the other two replicates. For debugging, please set `-c 1` and retry with the permissive thresholds, and if you get `100%` of the peaks in the `Confirmed` set, that would indicate a low colocalization of binding sites across your replicates. You may revisit your sample/library preparation, sequencing, and peak calling protocols if a low colocalization is not expected. If expected, you may consider lowering `-c` if the number of discarded peaks is too high for your use case. 

If after a call to MSPC with `-c 1 -w 1e-1 -s 1e-2`, you still do not get `100% Confirmed`, please let me know, and we could go deeper with debugging.

**Comment by AnthonyDohertyTCD** [comment] 2022-09-13 10:07
@VJalili 

Thank you for the continued help. 

With the below command I get 100% confirmed peaks as expected. 

`mspc -i P-BMI-Rep1_peaks.broadPeak P-BMI-Rep2_peaks.broadPeak P-BMI-Rep3_peaks.broadPeak -r Bio -w 1e-1 -s 1e-2 -c 1 --parser parser_config.json`

![Screenshot 2022-09-13 at 10 50 37](https://user-images.githubusercontent.com/62442736/189870746-bdd79079-42dd-48c7-9040-8cb123b345f4.png)

Could I ask you to clarify what degree of overlap is needed for a peak to be called in biological replicates (ie do the peak co-ordinates need to overlap exactly). Sorry if this is made clear in the documentation. I am a wet lab scientist relatively new to these types of analyses. 

_Finally my peak call arguments was as follows:_

`macs2 callpeak -t ${IP_BAM}.dedup.bam -c ${Input_BAM}.dedup.bam -f BAMPE -g hs -n ${IP_BAM} --broad --broad-cutoff 0.05 --nomodel --extsize 200 --outdir Macs2output`  

Could how I called the peaks be causing my issue? The bigwig genome browser tracks for each biological replicate look very similar and I was not expecting to lose so many peaks. 

All the best, 

Anto

**Comment by VJalili** [comment] 2022-09-13 21:52
>Could I ask you to clarify what degree of overlap is needed for a peak to be called in biological replicates (ie do the peak co-ordinates need to overlap exactly).

Glad that worked. At this point, I would revert the thresholds to more sensible values and retry with a relaxed `-c` if setting `-c 3` causes discarding a lot of peaks in your experiment. A "proper" value of `-c` highly depends on your experiment setup; though in general a degree of discrepancy is expected between biological replicates. You may set `-c 2` or `-c 1` and use a bit more stringent thresholds, which would lead keeping strong evidences (binding sites) that happen to not overlap with other peaks. 


> Finally my peak call arguments was as follows:
> ```
> macs2 callpeak -t ${IP_BAM}.dedup.bam -c ${Input_BAM}.dedup.bam -f BAMPE -g hs \
> -n ${IP_BAM} --broad --broad-cutoff 0.05 --nomodel --extsize 200 --outdir Macs2output
>```
>Could how I called the peaks be causing my issue? The bigwig genome browser tracks for each biological replicate look very similar and I was not expecting to lose so many peaks.

@fernandoPalluzzi Any thoughts on this?

**Comment by VJalili** [comment] 2022-10-22 01:46
@AnthonyDohertyTCD I hope these explanations clarified the situation. I'm closing the issue, but please feel free to reopen if you have related issues, or create a new issue for other questions.

**Closed by VJalili** 2022-10-22 01:46 UTC
Labels: question
