### ISSUE TITLE
I run rmspc  had met some problems

### ISSUE THREAD

**Issue by amateur-boy** [Genometric/MSPC#194] opened 2023-04-14 08:09 UTC
when i want to run the program to calculate the peak calling in Rstudio of windows,The program will report an error，Does this program not support Windows？ Thansk！

```
library(rmspc)
> results <- mspc(input = input, replicateType = "Technical",
+                 stringencyThreshold = 1e-8,
+                 weakThreshold = 1e-4, gamma = 1e-8,
+                 keep = FALSE,GRanges = TRUE,
+                 multipleIntersections = "Lowest",
+                 c = 2,alpha = 0.05)
```

> Error in `process_initialize(self, private, command, args, stdin, stdout, …`:
! Native call to `processx_exec` failed
Caused by error in `chain_call(c_processx_exec, command, c(command, args), pty, pty_options, …`:
! Command 'dotnet' not found @win/processx.c:982 (processx_exec)
Type .Last.error to see the more details.

**Comment by VJalili** [comment] 2023-04-14 13:00
@MeriemBahda, we would greatly appreciate your expertise on this. Could you please share your thoughts?

**Comment by MeriemBahda** [comment] 2023-04-16 01:56
Hello to you both , 
Yes of course @VJalili. Thank you for reaching out @amateur-boy! The program does work on Windows. Have you downloaded .NET 5.0 ( or newer ) prior to installing and using the rmspc package ?  The error you received `Command 'dotnet' not found @win/processx.c:982 (processx_exec)` suggests that the function mspc can't find the `dotnet` command. If you have not previously installed .NET 5.0,  you may install it following [these instructions](https://dotnet.microsoft.com/download/dotnet/5.0).

**Comment by amateur-boy** [comment] 2023-04-18 03:56
great!!!

**Comment by VJalili** [comment] 2023-04-18 04:01
Thank you @MeriemBahda! @amateur-boy I suppose the issue is resolved now, so I am closing this issue, but please feel free to reopen it if you have similar questions.

**Closed by VJalili** 2023-04-18 04:01 UTC
