### ISSUE TITLE
DOTNET CIFS version issues

### ISSUE THREAD

**Issue by TheRealQuantumCheese** [Genometric/MSPC#158] opened 2021-12-13 15:30 UTC
Environment: Rocky Linux 8.5 (and 8.4)
The bundled version of Dotnet in the linux-x64.zip has an issue with CIFS calls depending on how they are called, resulting in empty files being created followed by access denied upon writing:

```
.::....Saving Results....::.
Error: Access to the path '/mnt/redacted/ConsensusPeaks_mspc_peaks.txt' is denied.
```

See here for the bug:  https://github.com/dotnet/runtime/issues/42790

The workaround i used was from here: https://forums.docker.com/t/a-workaround-for-net-writing-to-cifs-volume-yielding-empty-file-and-access-to-the-path-is-denied/110872

**Comment by VJalili** [comment] 2021-12-14 00:26
Thanks for reporting this. As you've mentioned, it seems the workaround is: 

> mounting cifs shares using the `nobrl` option
https://github.com/dotnet/runtime/issues/42790#issuecomment-817758887

It also seems that this issue is mainly related to an older version of .NET. The current latest release of MSPC, [v5.4.0](https://github.com/Genometric/MSPC/releases/tag/v5.4.0), is targeting [.NET 5.0](https://github.com/Genometric/MSPC/blob/bf69dbdda407d79004708ba7ef45c471364fc6ed/CLI/CLI.csproj#L5) and it seem the issue resolved in this version of .NET. Could you please rerun using MSPC v5.4.0 and check if you're still experiencing the same issue?

**Comment by TheRealQuantumCheese** [comment] 2021-12-15 15:38
Yes there is a 'workaround' but i'm not certain it is working- the link i gave had an investigation by "tai-yi" where of 4 ways of writing a file out, only one worked.  i don't want to change my mount method just for this.

I am using the version 5.4.0  of your MSPC which is "self contained"? so using a 'fixed' dornet i assumed.

The only other comparison i had while looking into this is a version running on an old server (centos 7) which does not suffer from this issue.  that too is mspc 5.4.0 and it does not use the mount-option workaround to work. (and is mounting the same windows shared ntfs shares)

Happy to help if i can, this was a ***** to work out!

**Comment by VJalili** [comment] 2021-12-17 02:04
> where of 4 ways of writing a file out, only one worked.

Am I correct in assuming you currently have a setup where MSPC writes successfully to CIFS mount?

**Comment by TheRealQuantumCheese** [comment] 2021-12-17 11:46
Yes, but only using the previously mentioned mount workaround. So a 
temporary solution.

**Comment by VJalili** [comment] 2021-12-18 19:03
Based on the issues you referenced, it seems the CIFS mount issue is resolved on the .NET side. Hence, I updated target framework to .NET 6.0 (current latest release) and published [MSPC v5.5.0](https://github.com/Genometric/MSPC/releases/tag/v5.5.0) release. Please try this version of MSPC and let me know if it resolves the challenges you're facing.

**Comment by TheRealQuantumCheese** [comment] 2021-12-22 09:36
I went to test the latest version i found here: https://github.com/Genometric/MSPC/releases/download/v5.5.0/linux-x64.zip 
however when run: mspc --version reports V5.4.0 
That is clearly not correct, will test when version reports correctly

**Comment by VJalili** [comment] 2021-12-22 18:42
Yes, you're right, the version number was not reflected correctly. I updated the binaries in the release, please use the updated binaries. Regardless of the version number, both the previous and current binaries are targeting `.NET 6.0`, hopefully, the issue is resolved in this `.NET` version.

**Closed** 2021-12-22 18:47 UTC
Labels: .NET
