### ISSUE TITLE
Curious scores equal 0 (zero) in MSPC consensus file for replicated stringent peaks

### ISSUE THREAD

**Issue by AlexBlais74** [Genometric/MSPC#131] opened 2020-09-12 23:07 UTC
Hello
I am using mspc version 4.0.1
I am obtaining an unexpected behavior for the results of the MSPC analysis, where peaks (ATAC-seq, called by MACS2) that are of very high confidence get a score of zero while much lower confidence consensus peaks get an above-zero score. I would like an explanation to help me understand if this is the expected behavior or if I am doing something wrong.

The command I used with MSPC was
```
dotnet mspc.dll \
-i Sample_01_peaks.mspcBED \
Sample_02.mspcBED \
Sample_03.mspcBED \
Sample_04.mspcBED \
Sample_05.mspcBED \
Sample_06.mspcBED \
-r bio -w 1e-5 -s 1e-10 -d 6 \
--output MSPC_output
```

Peaks are called with MACS2 with p-value cutoff left at default value.  The distribution of scores calculated in R for one of my 6 replicates is as follows:
```
       V7                V8                 V9                V10        
 Min.   :  1.251   Min.   :   3.132   Min.   :   1.374   Min.   :   0.0  
 1st Qu.:  4.029   1st Qu.:  10.598   1st Qu.:   8.617   1st Qu.:  56.0  
 Median :  6.339   Median :  24.337   Median :  22.179   Median : 106.0  
 Mean   :  9.752   Mean   :  93.057   Mean   :  90.696   Mean   : 150.1  
 3rd Qu.: 13.196   3rd Qu.:  89.245   3rd Qu.:  86.703   3rd Qu.: 189.0  
 Max.   :110.091   Max.   :3742.200   Max.   :3735.730   Max.   :1555.0  
```

V7: fold-change at peak summit
V8: -log10pvalue at peak summit
V9: -log10qvalue at peak summit
V10: relative summit position to peak start

In the consensus peaks:
```
chr9    69304509        69304862        MSPC_Peak_116502        0
chr9    69305100        69305173        MSPC_Peak_116501        12.332
chr9    69305437        69306418        MSPC_Peak_116500        0
```

Same peaks, in the ConsensusPeaks_mspc_peaks.txt file:
```
chr     start   stop    name    -1xlog10(p-value)       xSqrd   -1xlog10(Right-Tail Probability)        -1xlog10(AdjustedP-value)
chr9    69304509        69304862        MSPC_Peak_116502        0       3470.525        0       0
chr9    69305100        69305173        MSPC_Peak_116501        12.332  56.79   12.332  12.312
chr9    69305437        69306418        MSPC_Peak_116500        0       8933.281        0       0
```

The corresponding peaks, in the first of 6 input files from MACSs are:
```
chr9	69304514	69304845	peak_152259	1257	.	4.95997	128.515	125.789	57
chr9	69305100	69305173	peak_152260	123	.	2.02626	14.4003	12.3318	49
chr9	69305445	69306393	peak_152261	3642	.	8.83607	367.663	
```

thus -log10(q-values) of about 125, 12 and 367.

Here is a visual example to explain:
![image](https://user-images.githubusercontent.com/53985544/93006339-fcfa9900-f528-11ea-8c66-041a2e626995.png)

A plot of the xSqrd vs -1xlog10(Right-Tail Probability) gives me this, so at values of chi-square above ~1500, the scores get very bad. Is this a problem with the program not being able to calculate an accurate probability with huge xSqrd values?

![image](https://user-images.githubusercontent.com/53985544/93006459-85c60480-f52a-11ea-9943-6750a30e2384.png)

I don't understand how such a great peak (MSPC_Peak_116500, on the right on the graph) can get a poorer "score" than a very short peak. I must be getting something wrong?

Thanks for your help

Alex

**Comment by VJalili** [comment] 2020-09-13 14:57
Thanks for the feedback @AlexBlais74! 

Few points to consider: 

1. 
    ```
    chr9	69304514	69304845	peak_152259	1257	.	4.95997	128.515	125.789	57
    chr9	69305100	69305173	peak_152260	123	.	2.02626	14.4003	12.3318	49
    chr9	69305445	69306393	peak_152261	3642	.	8.83607	367.663	
    ```

    By default, MSPC reads the 5th column for p-values, that are `1257`, `123`, and `3642`, and assumes they're in `-Log10` form.      But it seems you're expecting MSPC to read the 9th column for p-values, is that correct? If so,  please [refer to this documentation](https://genometric.github.io/MSPC/docs/cli/parser) for how to configure the parser,     and [set MSPC to apply them](https://genometric.github.io/MSPC/docs/cli/args#input-parser-configuration).

2. If you still want to use the 5th column, it seems your p-values are in `-10xLog10` format, and not `-Log10`. If so, you can [configure MSCP to read input p-value format correctly.](https://genometric.github.io/MSPC/docs/cli/parser#p-value-format)

3. MSPC can process peaks with very low p-value; e.g., see the following test that asserts processing peaks with p-values `5e-323`: 
     https://github.com/Genometric/MSPC/blob/4ed35ba20b937b243fe2673903c76acd5ad36833/Core.Tests/SetsAndAttributes/Confirmed.cs#L184-L209

    However, that applies to the X-squared for the chi-squared distribution, and peaks with very high (significant) X-squared will have `0` right-tail probability (as you see in your experiment). You may double-check it [with this online calculator](http://courses.atlas.illinois.edu/spring2016/STAT/STAT200/pchisq.html). Converting a right-tail probability of `0` to `-Log10` format will output `∞` (infinity), and since this value or `NaN` are not acceptable by some programs, MSPC outputs `0`. See: 

    https://github.com/Genometric/MSPC/blob/4ed35ba20b937b243fe2673903c76acd5ad36833/CLI/Export/Exporter.cs#L141-L152

     We might be able to change the hard-coded `"0"` to `"Inf"` or `"-1"` (or any better value) if that seems a better alternative. Please feel free to PR if you've a suggestion.

ping @marziacremona

**Comment by AlexBlais74** [comment] 2020-09-13 15:37
Thanks for the answer!

I apologize for not being clear in my original post.
I am taking the output of MACS2 (v2.2.7.1) and do two things:
-filter out the narrowPeak file to remove blacklisted regions
-employ awk to convert the filtered narrowpeak file and make it compatible for MSPC
```
# filter narrowpeak files from MACS to remove blacklisted regions (mm9 genome):
bedtools intersect -v \
-a my_peaks.narrowPeak \
-b mm9-blacklist.bed \
>my_peaks.filtered.narrowPeak

# next, convert filtered narrowpeak files from MACS to bed, ranked by decreasing q value (9th column) and output this q value in the 5th column of a pseudo-BED file format, so MSPC is happy
sort -k9,9nr \
my_peaks.filtered.narrowPeak |\
awk -F "\t" '{printf($1"\t"$2"\t"$3"\t"$4"\t"$9"\n")}' - \
>my_peaks.filtered.mspcBED
```
The narrowPeak format described by MACS2 is here, under "Output files"
https://github.com/macs3-project/MACS
As you can see, column #9, which I am using, is -log10qvalue at peak summit (NOT multiplied by 10 or 100)
This is different from MACS' column #5, which is indeed a 10-fold multiplication of the p or q value.

In the MACS2 output which I showed in my original post:
`chr9	69304514	69304845	peak_152259	1257	.	4.95997	128.515	125.789	57`

you can see that indeed, column 5 is simply column 9 multiplied by 10.
And I confirm that for the input I feed into MSPC, I am using column 9 (non-multiplied -log10 q value):
`chr9    69304514        69304845        peak_152259     125.789`


Note that in my MACS2 output, I have some -log10(qvalue) larger than 3000 (see summary in column V9, in my original post)! Is the program able to handle such large numbers?

I presume that most users would want to have some way to tell apart peaks that have a consensus MSPC score of zero because they are VERY BAD from those that have also a value of zero but because they are VERY GOOD. It is definitely essential to me. So I would certainly welcome the option to output -1 or "Inf" (or "awesome peak!") in those circumstances.

I am really bad at statistics, but are these observations putting in question the validity of using chi-squared distribution to calculate scores from replicates, or are they only underscoring the limitations of programs that calculate probabilities for extreme values from this distribution?

Thanks again for your help!

Alex

**Comment by VJalili** [comment] 2020-09-14 12:34
> And I confirm that for the input I feed into MSPC, I am using column 9 (non-multiplied -log10 q value):
chr9 69304514 69304845 peak_152259 125.789

So you are passing a JSON object containing parser configuration?!

**Comment by AlexBlais74** [comment] 2020-09-14 12:46
No, I am not configuring any parser. I follow the instructions here: 

> MSPC takes as input a tab-delimited file in BED format for each replicate, each containing enriched regions (aka peaks) called with a permissive p-value threshold.

> The fifth column represents the p-value, and by default, MSPC expects it be in -Log10 format 

MY input files are created as described by the code I inserted in my previous message (the sort|awk command). That command takes column 9 of the MACS2 narrowPeak output and places it in position 5, to comply with the MSPC expected format. 

Is this not sufficient?

**Comment by VJalili** [comment] 2020-09-14 13:00
Yes, that is sufficient. Using [parser configuration](https://genometric.github.io/MSPC/docs/cli/parser) would have been an easier option as you would not had to convert your files.

**Comment by AlexBlais74** [comment] 2020-09-14 13:40
I just tried with a parser config, using files out of MACS2, and I am getting the exact same results.

**Comment by VJalili** [comment] 2020-09-14 17:29
I made the changes in PR #132 and published a new release: https://github.com/Genometric/MSPC/releases/tag/v4.0.2

Please use this version and let me know if it resolves the issue you're experiencing.

**Comment by AlexBlais74** [comment] 2020-09-16 19:33
Hi, sorry for the delay in trying out the new version.
I confim this is working:
Outputs from versions 4.0.1 and 4.0.2 copied below.
Thanks 
Alex

```
head ConsensusPeaks.v4.0.2.bed
chr     start   stop    name    -1xlog10(p-value)
chr1    4561313 4562301 MSPC_Peak_59107 inf
chr1    4696178 4696908 MSPC_Peak_59106 inf
chr1    4737043 4737294 MSPC_Peak_59105 143.126
chr1    4737974 4738156 MSPC_Peak_59104 93.65
chr1    4738225 4738504 MSPC_Peak_59103 101.138
chr1    4741394 4741802 MSPC_Peak_59102 inf
chr1    4770252 4770439 MSPC_Peak_59101 71.239
chr1    4775393 4776344 MSPC_Peak_59100 inf
chr1    4788357 4788835 MSPC_Peak_59099 inf

head ConsensusPeaks.v4.0.1.bed
chr     start   stop    name    -1xlog10(p-value)
chr1    4561313 4562301 MSPC_Peak_91076 0
chr1    4696178 4696908 MSPC_Peak_91074 0
chr1    4737043 4737294 MSPC_Peak_91069 143.126
chr1    4737974 4738156 MSPC_Peak_91066 93.65
chr1    4738225 4738504 MSPC_Peak_91064 101.138
chr1    4741394 4741802 MSPC_Peak_91062 0
chr1    4770252 4770439 MSPC_Peak_91061 71.239
chr1    4775393 4776344 MSPC_Peak_91060 0
chr1    4788357 4788835 MSPC_Peak_91059 0

```

**Comment by VJalili** [comment] 2020-09-17 04:26
I'm glad that works. I'm closing this issue; please feel free to reopen it if you encounter any similar issues.

**Closed by VJalili** 2020-09-17 04:26 UTC
Labels: documentation, question
